# Usa una imagen de Python como base
FROM python:3.8

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de requisitos
COPY requirements.txt /app/

# Instala las dependencias del orquestador
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código del orquestador
COPY . /app/

# Define el comando predeterminado para ejecutar el orquestador
CMD ["python", "orquestador.py"]
